# Generated by Django 2.2 on 2019-04-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190421_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='created_by',
        ),
    ]
